service: blocklist-aggregator
app: blocklist-aggregator
org: dallinwright01

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-dynamodb-local
  - serverless-tag-api-gateway

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: eu-west-1
  timeout: 900 # The default is 60
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:*"
        - "cloudwatch:*"
        - "invoke-api:*"
      Resource:
        - "*"
  environment:
    ES_REGION: eu-west-1
    ES_ENDPOINT: https://vpc-clillab-d5cxi6isskimi4uqzrpihczhqa.eu-west-1.es.amazonaws.com
    ES_INDEX: blocklist
    BASE_REPO: https://github.com/firehol/blocklist-ipsets.git
    BLOCK_LISTS: "blocklist*.ipset,dshield*.ipset,zeus*.ipset"
  stackTags:
    Name: ${self:service}
    service_name: ${self:service}
    environment: ${opt:stage, self:provider.stage}
    managed_by: sls

custom:
  apiGatewayTags:
    Name: ${self:service}-APIGateway
    environment: ${opt:stage, self:provider.stage}
    managed_by: sls
    stackName: ${self:service}
    infrastructure_tier: APIGateway

functions:
  index:
    handler: src/index.handler
    vpc:
      securityGroupIds:
        - sg-b98dfbc4
        - sg-000728d0503bebdb9
      subnetIds:
        - subnet-cc906296
#    events:
#      - http:
#          path: create
#          method: get
#          cors: true
#      - http:
#          path: create
#          method: post
#          cors: true
