service: blocklist-aggregator
app: blocklist-aggregator
org: dallinwright01

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-dynamodb-local
  - serverless-tag-api-gateway

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: eu-west-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:*"
        - "cloudwatch:*"
        - "invoke-api:*"
      Resource:
        - "*"
  environment:
    TABLE_NAME: blocklist-${opt:stage, 'dev'}
  stackTags:
    Name: ${self:service}
    service_name: ${self:service}
    environment: ${opt:stage, self:provider.stage}
    managed_by: sls

custom:
  apiGatewayTags:
    Name: ${self:service}-APIGateway
    environment: ${opt:stage, self:provider.stage}
    managed_by: sls
    stackName: ${self:service}
    infrastructure_tier: APIGateway

functions:
  index:
    handler: src/index.handler
    events:
      - http:
          path: create
          method: get
          cors: true
      - http:
          path: create
          method: post
          cors: true
